### ISSUE TITLE
Can't run on mac.

### ISSUE THREAD

**Issue by yangwuan55** [caprica/vlcj-javafx#20]
![image](https://user-images.githubusercontent.com/5218120/58697984-f0524000-83cc-11e9-969b-fdb979389d23.png)

```

Exception in Application constructor
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class AnimationTimerJavaFXDirectRenderingTest
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$159(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$165(LauncherImpl.java:819)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$179(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$177(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$178(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:195)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:119)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:174)
	at JavaFXDirectRenderingTest.<init>(JavaFXDirectRenderingTest.java:123)
	at AnimationTimerJavaFXDirectRenderingTest.<init>(AnimationTimerJavaFXDirectRenderingTest.java:33)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:206)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:192)
	... 14 more
Exception running application AnimationTimerJavaFXDirectRenderingTest

```

**Comment by caprica** [comment]
Problem is in your environment.

**Comment by yangwuan55** [comment]
![image](https://user-images.githubusercontent.com/5218120/58779056-46122c80-8607-11e9-86cd-a34c6b3f4fa1.png)
I already install vlc,is that what you mean?

**Comment by caprica** [comment]
Looks to me like the native library can't be found.

I have tested vlcj against latest OSX and it worked for me the last time I tested it.

**Comment by yangwuan55** [comment]
So what library shoud I install?
help please...

**Comment by yangwuan55** [comment]
![image](https://user-images.githubusercontent.com/5218120/58781285-1c103880-860e-11e9-9341-24e092a6433d.png)
This library is load failed.But I don't know how to install it.

**Comment by caprica** [comment]
Did you install VLC using the official package for OSX? Did you install it in the normal way?

**Comment by caprica** [comment]
I just spotted that you use "casks".

Try installing the official package from VideoLAN instead of using casks.

**Comment by yangwuan55** [comment]
Thank you very much,I reinstall the package and work well.
