### ISSUE TITLE
Could not initialize class uk.co.caprica.vlcj.binding.LibVlc

### ISSUE THREAD

**Issue by alrickemilien** [caprica/vlcj-javafx#21]
**Context :** 

- Commit 1c36222b5ddcc9f27ff732ad6597d61f0d424c4d at Jun 22, 2019 
- Ubuntu 18
- VLC installed with` apt-get install -y vlc libvlc-dev`
- Java 1.8.0_181

**Issue :**

Encountering an issue of LibVLC library loading when `new MediaPlayerFactory()` is called into `JavaFXDirectRenderingTest` constructor.

Here is the stack trace :

![Screenshot from 2019-07-10 16-22-29](https://user-images.githubusercontent.com/23482614/60977198-55377900-a32f-11e9-8b23-730832b2cdce.png)

Here is the content of `/usr/lib/vlc` :

libvlc_vdpau.so
libvlc_vdpau.so.0
libvlc_vdpau.so.0.0.0
lua
plugins
vlc-cache-gen

Here is the content of `/usr/lib/vlc/plugins` :

access
access_output
audio_filter
audio_mixer
audio_output
codec
control
demux
gui
lua
meta_engine
misc
mux
notify
packetizer
plugins.dat
services_discovery
stream_filter
stream_out
text_renderer
vdpau
video_chroma
video_filter
video_output
video_splitter
visualization

**Comment by alrickemilien** [comment]
By adding at start of `JavaFXDirectRenderingTest` class as follow :
```
static {
      NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "/usr/lib/vlc");
}
```

I got the following stack trace usefull info :
```
Caused by: java.lang.RuntimeException: Failed to find minimum required VLC version 3.0.0, found 2.2.7 Umbrella in /usr/lib/libvlc.so
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:190)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:175)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:105)
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:128)
	at uk.co.caprica.vlcj.javafx.test.JavaFXDirectRenderingTest.<init>(JavaFXDirectRenderingTest.java:133)
	at uk.co.caprica.vlcj.javafx.test.AnimationTimerJavaFXDirectRenderingTest.<init>(AnimationTimerJavaFXDirectRenderingTest.java:35)

```

**Comment by caprica** [comment]
Well, this is one of those rare moments in software where the error actually tells you what's wrong.

```
   Failed to find minimum required VLC version 3.0.0, found 2.2.7 Umbrella in /usr/lib/libvlc.so
```
So your version of VLC does not meet the minimum requirements.
