### ISSUE TITLE
Exception running your example

### ISSUE THREAD

**Issue by fearchannel** [caprica/vlcj-javafx#23]
```
Exception in Application constructor
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Unable to construct Application instance: class videoplayer.JavaFXDirectRenderingTest
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:907)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InstantiationException
	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$7(LauncherImpl.java:819)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245)
	... 1 more
```

I'm trying to run you sample JavaFXDirectRenderingTest, cause I want to show a RTSP stream on a JavaFX software, but this is the output when I run your sample. I'm doing something wrong? I've just added vlc 4.1.0 at my build.gradle and changed the VIDEO_FILE address

**Comment by caprica** [comment]
It's impossible to say from that stacktrace as there is no vlcj or vlcj-javafx code in it.

However, the most likely problem is a failure to load the native LibVLC library. Did you install VLC correctly?

Did you follow the vlcj tutorials to check the native LibVLC library could be loaded?

**Comment by fearchannel** [comment]
Yes, double checked it. My others examples run just nicely.

**Comment by caprica** [comment]
Well then I'm afraid you'll need to do some more digging, because based on what you've posted it's impossible for me to tell where it's going wrong. There's an exception thrown by your application constructor, and I don't see any vlcj code in your stacktrace.

RTSP is no different to playing anything else. HeadlessMediaPlayer is really only intended for cases where you don't want to display video.

**Comment by fearchannel** [comment]
Right, okay. Which one of the samples show how to create and execute an simple video player with Canvas at JavaFX? Thank you for your time!

**Comment by caprica** [comment]
There's this: https://github.com/caprica/vlcj-javafx

And this: https://github.com/caprica/vlcj/issues/883

There should be enough there to get you going.

**Comment by fearchannel** [comment]
Great! Your library is amazing. I'm just having some trouble to put a EmbeddedMediaPlayer in my Canvas. Can you give me a tip in how to do it?

This is my currently code:


```
    @FXML
    private Canvas canvas;

    private PixelWriter pixelWriter;

    private final WritablePixelFormat<ByteBuffer> pixelFormat;

    private final MediaPlayerFactory mediaPlayerFactory;

    private final EmbeddedMediaPlayer mediaPlayer;

    private final String VIDEO_FILE = "/home/leonardo/Documentos/newvideo.mp4";

    public ViewerController() {
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        canvas = new Canvas(width, height);

        pixelWriter = canvas.getGraphicsContext2D().getPixelWriter();
        pixelFormat = PixelFormat.getByteBgraInstance();

        mediaPlayerFactory = new MediaPlayerFactory();
        mediaPlayer = mediaPlayerFactory.newEmbeddedMediaPlayer();

    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        mediaPlayer.playMedia(VIDEO_FILE);
    }
}
```

My fxml just have an anchorpane and a canvas

**Comment by caprica** [comment]
If you're using JavaFX, you MUST use the CallbackVideoSurface to render your video.

Really the best thing to do is to start with this example: https://github.com/caprica/vlcj-javafx/blob/pixelbuffer-test/src/test/java/uk/co/caprica/vlcj/javafx/test/WritableImageDemo.java

Put that example into your own project, get it working, and then adapt it to your needs once you understand how it's working. That example is a really nicely performing and actually quite simple implementation (no timers or anything to worry about), so it really should be your starting point.

You will need JavaFX 13 for that particular example since it uses the new PixelBuffer that came with JavaFX 13, and it is this that gives really nice performance, and definitely better performance than using PixelWriter.

This example 100% works, you can also refer to https://github.com/caprica/vlcj/issues/883 to see the history of that example (I use it on Linux, the other guys who posted in that issue I think all used OSX, or MacOS or whatever its name is now).

**Comment by fearchannel** [comment]
FX13 should use JDK13 too, right?
